### ISSUE TITLE
NOT NULL check constraint; SYS_CT_14178 table: RTCABO_CUSTOMER column: TENANT_ID

### ISSUE THREAD

**Issue by ghost** [mariodavid/rtcab-ordermanagement#9]
Hi Mario, 

I;m getting the following issue: 

Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_14178 table: RTCABO_CUSTOMER column: TENANT_ID

1) $ ./gradlew setupTomcat deploy createDb start --stacktrace
2) Error: NOT NULL check constraint; SYS_CT_14178 table: RTCABO_CUSTOMER column: TENANT_ID

Any ideas?

Thank you

Regards, 
Jiri

**Comment by mariodavid** [comment]
Hi,

please see my comment here: https://github.com/mariodavid/rtcab-ordermanagement/issues/10#issuecomment-404926273

The issue is the same.
Bye
Mario

**Comment by mariodavid** [comment]
done in #3 --> video with explanation: https://youtu.be/s3AFVtHOByU

Bye
Mario

**Comment by ghost** [comment]
Thanks, works for me now!

PS: 
Sorry for the late feedback. Somehow overlooked that you worked on the issue!
